export const userTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT"
};

export const maidTypes = {
  SELECTED_MAID: "SELECTED_MAID"
};

export const maidsTypes = {
  FETCH_MAIDS: "FETCH_MAIDS"
};

export const searchTypes = {
  QUICK_SEARCH_TYPE: "QUICK_SEARCH_TYPE",
  FILTER_SEARCH: "FILTER_SEARCH"
};

export const bookingTypes = {
  INCREASE_NEW_BOOKING_BADGE: "INCREASE_NEW_BOOKING_BADGE",
  DECREASE_NEW_BOOKING_BADGE: "DECREASE_NEW_BOOKING_BADGE",
  MYBOOKING: "MYBOOKING"
};

export const fetchType = {
  FETCHED_BOOKING_EMPLOYER: "FETCHED_BOOKING_EMPLOYER",
  FETCHED_BOOKING_MAID: "FETCHED_BOOKING_MAID",
  RECEIVE_ERROR: "RECEIVE_ERROR"
}
